# action.yml
name: 'Git Anti Virus Scan'
description: 'Anti Virus scan for malicious files in a Git repository'
inputs:
  full:  
    description: 'Full history scan'
    required: false
  options:
    description: 'Additional options for clamscan command'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/djdefi/gitavscan:nightly'
  args:
    - '/gitscan.sh'
    - ${{ inputs.full }}
    - ${{ inputs.options }}
branding:
  icon: 'shield'  
  color: 'orange'
